import type { MetadataRoute } from "next";

/**
 * Web App Manifest — makes the site installable ("Add to Home Screen").
 * Next serves this at /manifest.webmanifest and auto-links it in <head>
 * because the file lives at the root of the app directory.
 *
 * The icons are generated by the app/pwa-icon/[variant] route (the same
 * ImageResponse mark as the favicon), so there are no PNGs to keep in sync.
 *
 * There is deliberately no service worker: neither Chrome's install criteria
 * nor iOS "Add to Home Screen" require one, and a cache layer over daily-
 * refreshed price data would risk showing stale numbers — a worse failure than
 * having no offline mode.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    // `id` pins app identity across manifest edits: without it the browser keys
    // the installed app on start_url, so changing that later would orphan the
    // icon already on a user's home screen.
    id: "/",
    name: "Wood Wiz — South African firewood prices per kg",
    short_name: "Wood Wiz",
    description:
      "Compare braai, fireplace and smoking wood prices from the vendors who deliver to your city, normalised to rand per kilogram.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    // Match the light default surface (stone-50) so a launched-from-home-screen
    // window doesn't flash a mismatched colour before first paint.
    background_color: "#fafaf9",
    theme_color: "#fafaf9",
    icons: [
      { src: "/pwa-icon/192", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/pwa-icon/512", sizes: "512x512", type: "image/png", purpose: "any" },
      // Android masks maskable icons to a device-chosen shape; this variant
      // keeps the mark inside the ~80% safe zone so it isn't clipped.
      { src: "/pwa-icon/maskable", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
